apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: bookmgmtsvc-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bookmgmtsvc 
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmgmtsvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: bookmgmtsvc
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bookmgmtsvc
    spec:
      containers:
      - name: bookmgmtsvc
        image:  {{ .Values.image.name }}:{{ .Values.image.tag }} 
        envFrom:
        - configMapRef:
            name: bookmgmtsvc
        resources:
          limits:
            cpu: "0.5"
          requests:
            cpu: "0.5"    

---
apiVersion: v1
kind: Service
metadata:
  name: bookmgmtsvc
  labels:
    app.kubernetes.io/name: bookmgmtsvc
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/name: bookmgmtsvc
