apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: librarysvc-hpa 
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: librarysvc 
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 90 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: librarysvc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: librarysvc
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: librarysvc
    spec:
      containers:
      - name: librarysvc
        image:  {{ .Values.image.name }}:{{ .Values.image.tag }} 
        envFrom:
        - configMapRef:
            name: librarysvc
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "1"    

---
apiVersion: v1
kind: Service
metadata:
  name: librarysvc
  labels:
    app.kubernetes.io/name: librarysvc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/name: librarysvc
